### ISSUE TITLE
Missing run command to add 'remote'

### ISSUE THREAD

**Issue by Narven** [adam-lynch/developing-an-electron-edge#2]
Almost at the beginning of the file in the part: **Opening files**, after this line:

_There’s only one problem. This module is only available to the main process (main.js), but not our renderer process (index.html and index.js). Luckily, there is an easy solution to this; use the remote module._

You should add something like:

Please run the following command: `npm install remote --save-dev`

**Comment by Narven** [comment]
I think is something basic... but it helps users in the beginning... to remember they have to run those commands. Later in the book you should skip those things.

**Comment by adam-lynch** [comment]
Oh no I'm sorry, this bit of code is actually out of date 😞. This is meant to be Electron's remote module, not a module from npm.

So to use it, you need to `require('electron').remote`.

In previous versions of Electron, you could `require('remote')` and it would use this internal module. 

See http://electron.atom.io/docs/api/remote/ for more information. Thanks for reporting this, we appreciate your feedback.
