### ISSUE TITLE
showOpenDialog issue

### ISSUE THREAD

**Issue by dc-cycle** [adam-lynch/developing-an-electron-edge#5]
Hi Adam,

I'm working in Chapter 5 of your Electron book, ( which I've been enjoying )  and am having trouble calling methods on the dialog module. 

const dialog = remote.require('dialog'); 

Does not seem to allow me access to  dialog.showOpenDialog({}), as it throws a "dialog.showOpenDialog is not a function" when I click on the open file link in my editor app.  I noticed that the remote module needs to be accessed differently than the book describes, ie, it's now:  

const remote = require('electron').remote; 

The above does enable access to the remote module. But I still can't access the dialog module methods, and can't seem to goggle anything on this. There must be an updated version accessing the dialog module. Can you help ?   Thanks !

**Comment by adam-lynch** [comment]
Thanks for reporting this. I'm sorry to say we made a stupid mistake. You're right, it should be `require('electron').remote`. I've updated all the examples in this repository. 

I've tried out the code again myself with the correction and it works fine, so I'd say you've made a small mistake somewhere. If the problem persists, please share your renderer code and I'll take a look.
