### ISSUE TITLE
Terrible experience buying a copy of the ebook from Gumroad

### ISSUE THREAD

**Issue by namedlock** [adam-lynch/developing-an-electron-edge#6]
I suggest you guys make your books available on z.cn, which is the amazon.com site in China. The buying experience was terrible due to the following facts:
* Gumroad seems to be banned by the Great Wall.
* Amazon.com ebook seems not to be accessed by the Chinese user.

It costed me loads of time to get rid off those obstacles.

**Comment by spartucus** [comment]
这本书我是在safaribooksonline.com上看完的。没试过Gumroad

**Comment by adam-lynch** [comment]
I'm really sorry to hear that. Thanks for the feedback!
